---
region: {{ cloudwatch_exporter_region }}
metrics:
{% for namespace in cloudwatch_exporter_namespaces %}
{% for metric in namespace.metrics %}
 - aws_namespace: {{ namespace.name }}
   aws_metric_name: {{ metric.name }}
   aws_dimensions: [{% for dimension in metric.dimensions %}{{ dimension.name }}{% if not loop.last %},{% endif %}{% endfor %}]
   aws_dimension_select_regex:
{% for dimension in metric.dimensions %}
     {{ dimension.name }}: [{{ dimension.select_regex }}]
{% endfor %}
   delay_seconds: {{ cloudwatch_exporter_delay_seconds }}
{% endfor %}
{% endfor %}
